a=int(input("ENTER THE A VALUE="))
b=int(input("ENTER THE B VALUE="))
print("add=",a+b)
print("sub=",a-b)
print("mul=",a*b)
print("Div=",a/b)
print ("mod=",a%b)
print ("expo=",a**b)
print("floor_division=",a//b)